name: lid_driven_cavity_problem
channels:
  - esss  # petsc4py, petsc
  - defaults
  - conda-forge  # pybind11
dependencies:
  - python==3.5.3
  - pytest
  - scipy
  - matplotlib
  - petsc4py
  - cython
  - pybind11
  - cmake  # for building pybind11 sources
  - asv
  - invoke
